#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(dead_code)]

use crate::api::cl_types::*;

type size_t = cl_size_t;

include!(concat!(env!("OUT_DIR"), "/cl_icd.rs"));

impl _cl_icd_dispatch {
    pub fn new() -> *mut _cl_icd_dispatch {
        Box::leak(Box::new(_cl_icd_dispatch {
            clGetPlatformIDs: Some(crate::api::platform::clIcdGetPlatformIDsLCL),
            clGetPlatformInfo: Some(crate::api::platform::clGetPlatformInfoLCL),
            clGetDeviceIDs: Some(crate::api::device::clGetDeviceIDsLCL),
            clGetDeviceInfo: Some(crate::api::device::clGetDeviceInfoLCL),
            clCreateContext: Some(crate::api::context::clCreateContextLCL),
            clCreateContextFromType: None,
            clRetainContext: None,
            clReleaseContext: None,
            clGetContextInfo: Some(crate::api::context::clGetContextInfoLCL),
            clCreateCommandQueue: None,
            clRetainCommandQueue: None,
            clReleaseCommandQueue: None,
            clGetCommandQueueInfo: None,
            clSetCommandQueueProperty: None,
            clCreateBuffer: Some(crate::api::memory::clCreateBufferLCL),
            clCreateImage2D: None,
            clCreateImage3D: None,
            clRetainMemObject: None,
            clReleaseMemObject: None,
            clGetSupportedImageFormats: None,
            clGetMemObjectInfo: None,
            clGetImageInfo: None,
            clCreateSampler: None,
            clRetainSampler: None,
            clReleaseSampler: None,
            clGetSamplerInfo: None,
            clCreateProgramWithSource: Some(crate::api::program::clCreateProgramWithSourceLCL),
            clCreateProgramWithBinary: None,
            clRetainProgram: None,
            clReleaseProgram: None,
            clBuildProgram: Some(crate::api::program::clBuildProgramLCL),
            clUnloadCompiler: None,
            clGetProgramInfo: None,
            clGetProgramBuildInfo: None,
            clCreateKernel: Some(crate::api::kernel::clCreateKernelLCL),
            clCreateKernelsInProgram: None,
            clRetainKernel: None,
            clReleaseKernel: None,
            clSetKernelArg: Some(crate::api::kernel::clSetKernelArgLCL),
            clGetKernelInfo: None,
            clGetKernelWorkGroupInfo: None,
            clWaitForEvents: None,
            clGetEventInfo: None,
            clRetainEvent: None,
            clReleaseEvent: None,
            clGetEventProfilingInfo: None,
            clFlush: None,
            clFinish: Some(crate::api::queue::clFinishLCL),
            clEnqueueReadBuffer: Some(crate::api::queue::clEnqueueReadBufferLCL),
            clEnqueueWriteBuffer: Some(crate::api::queue::clEnqueueWriteBufferLCL),
            clEnqueueCopyBuffer: None,
            clEnqueueReadImage: None,
            clEnqueueWriteImage: None,
            clEnqueueCopyImage: None,
            clEnqueueCopyImageToBuffer: None,
            clEnqueueCopyBufferToImage: None,
            clEnqueueMapBuffer: None,
            clEnqueueMapImage: None,
            clEnqueueUnmapMemObject: None,
            clEnqueueNDRangeKernel: Some(crate::api::queue::clEnqueueNDRangeKernelLCL),
            clEnqueueTask: None,
            clEnqueueNativeKernel: None,
            clEnqueueMarker: None,
            clEnqueueWaitForEvents: None,
            clEnqueueBarrier: None,
            clGetExtensionFunctionAddress: None,
            clCreateFromGLBuffer: None,
            clCreateFromGLTexture2D: None,
            clCreateFromGLTexture3D: None,
            clCreateFromGLRenderbuffer: None,
            clGetGLObjectInfo: None,
            clGetGLTextureInfo: None,
            clEnqueueAcquireGLObjects: None,
            clEnqueueReleaseGLObjects: None,
            clGetGLContextInfoKHR: None,
            clGetDeviceIDsFromD3D10KHR: std::ptr::null_mut(),
            clCreateFromD3D10BufferKHR: std::ptr::null_mut(),
            clCreateFromD3D10Texture2DKHR: std::ptr::null_mut(),
            clCreateFromD3D10Texture3DKHR: std::ptr::null_mut(),
            clEnqueueAcquireD3D10ObjectsKHR: std::ptr::null_mut(),
            clEnqueueReleaseD3D10ObjectsKHR: std::ptr::null_mut(),
            clSetEventCallback: None,
            clCreateSubBuffer: None,
            clSetMemObjectDestructorCallback: None,
            clCreateUserEvent: None,
            clSetUserEventStatus: None,
            clEnqueueReadBufferRect: None,
            clEnqueueWriteBufferRect: None,
            clEnqueueCopyBufferRect: None,
            clCreateSubDevicesEXT: None,
            clRetainDeviceEXT: None,
            clReleaseDeviceEXT: None,
            clCreateEventFromGLsyncKHR: None,
            clCreateSubDevices: None,
            clRetainDevice: None,
            clReleaseDevice: None,
            clCreateImage: None,
            clCreateProgramWithBuiltInKernels: None,
            clCompileProgram: None,
            clLinkProgram: None,
            clUnloadPlatformCompiler: None,
            clGetKernelArgInfo: None,
            clEnqueueFillBuffer: None,
            clEnqueueFillImage: None,
            clEnqueueMigrateMemObjects: None,
            clEnqueueMarkerWithWaitList: None,
            clEnqueueBarrierWithWaitList: None,
            clGetExtensionFunctionAddressForPlatform: None,
            clCreateFromGLTexture: None,
            clGetDeviceIDsFromD3D11KHR: std::ptr::null_mut(),
            clCreateFromD3D11BufferKHR: std::ptr::null_mut(),
            clCreateFromD3D11Texture2DKHR: std::ptr::null_mut(),
            clCreateFromD3D11Texture3DKHR: std::ptr::null_mut(),
            clCreateFromDX9MediaSurfaceKHR: std::ptr::null_mut(),
            clEnqueueAcquireD3D11ObjectsKHR: std::ptr::null_mut(),
            clEnqueueReleaseD3D11ObjectsKHR: std::ptr::null_mut(),
            clGetDeviceIDsFromDX9MediaAdapterKHR: std::ptr::null_mut(),
            clEnqueueAcquireDX9MediaSurfacesKHR: std::ptr::null_mut(),
            clEnqueueReleaseDX9MediaSurfacesKHR: std::ptr::null_mut(),
            clCreateFromEGLImageKHR: None,
            clEnqueueAcquireEGLObjectsKHR: None,
            clEnqueueReleaseEGLObjectsKHR: None,
            clCreateEventFromEGLSyncKHR: None,
            clCreateCommandQueueWithProperties: Some(
                crate::api::queue::clCreateCommandQueueWithPropertiesLCL,
            ),
            clCreatePipe: None,
            clGetPipeInfo: None,
            clSVMAlloc: None,
            clSVMFree: None,
            clEnqueueSVMFree: None,
            clEnqueueSVMMemcpy: None,
            clEnqueueSVMMemFill: None,
            clEnqueueSVMMap: None,
            clEnqueueSVMUnmap: None,
            clCreateSamplerWithProperties: None,
            clSetKernelArgSVMPointer: None,
            clSetKernelExecInfo: None,
            clGetKernelSubGroupInfoKHR: None,
            clCloneKernel: None,
            clCreateProgramWithIL: None,
            clEnqueueSVMMigrateMem: None,
            clGetDeviceAndHostTimer: None,
            clGetHostTimer: None,
            clGetKernelSubGroupInfo: None,
            clSetDefaultDeviceCommandQueue: None,
            clSetProgramReleaseCallback: None,
            clSetProgramSpecializationConstant: None,
            clCreateBufferWithProperties: None,
            clCreateImageWithProperties: None,
            clSetContextDestructorCallback: None,
        }))
    }
}
