[package]
name = "librecl-runtime"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2.126"
stdext = "0.3.1"
backtrace = "0.3.66"
once_cell = "1.13.0"
cxx = "1.0"
vulkano = "0.30.0"

[lib]
crate-type = ["cdylib"]
name = "lcl_icd_runtime"
path = "./lib.rs"
