[package]
name = "llvm_native"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[build-dependencies]
cmake = "0.1"
which = "4.2.5"
build-target = "0.4.0"
bindgen = "0.60.1"
