[package]
name = "lcloc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ocl_args = { path = "../../utils/ocl_args" }
librecl_compiler = { path = "../../src/compiler" }
