name: LibreCL verification

on:
  push:
    branches:
      - "develop"
  pull_request:
    branches:
      - "develop"
    paths:
      - "!doc/**"

jobs:
  build_test:
    strategy:
      matrix:
       os: ['ubuntu-latest', 'macOS-12']
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Ubuntu dependencies
        if: matrix.os == 'ubuntu-latest'
        run:
          sudo apt install -yqq ccache ninja-build libtbb-dev
      - name: Install macOS dependencies
        if: matrix.os == 'macOS-12'
        run:
          brew install ccache ninja tbb
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Create cache dir
        run: mkdir -p cache
      - name: Cache
        uses: actions/cache@v3
        with:
          path: cache
          key: llvm-${{ runner.os }}-${{ github.sha }}
          restore-keys: llvm-${{ runner.os }}-
      - name: Build LLVM
        run: ./build_llvm.sh
      - name: Configure LibreCL
        run: ./configure.sh
      - name: Build LibreCL
        run: cd build && ninja
        # TODO run tests
