name: LibreCL verification

on:
  push:
    branches:
      - "develop"
  pull_request:
    branches:
      - "develop"

jobs:
  build_test:
    strategy:
      matrix:
       os: ['ubuntu-22.04', 'macOS-12']
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: rui314/setup-mold@v1
      - name: Install Ubuntu dependencies
        if: matrix.os == 'ubuntu-22.04'
        run:
          sudo apt install -yqq ccache ninja-build libtbb-dev
      - name: Install macOS dependencies
        if: matrix.os == 'macOS-12'
        run:
          brew install ccache ninja tbb ncurses
          echo 'export PATH="/usr/local/opt/ncurses/bin:$PATH"' >> /Users/runner/.bash_profile
          echo "PKG_CONFIG_PATH=\"/usr/local/opt/ncurses/lib/pkgconfig\"" > $GITHUB_ENV
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Create cache dir
        run: mkdir -p cache
      - name: Cache
        uses: actions/cache@v3
        with:
          path: cache
          key: llvm-${{ runner.os }}-${{ github.sha }}
          restore-keys: llvm-${{ runner.os }}-
      - name: Build LLVM
        run: ./build_dependencies.sh
      - name: Configure LibreCL
        run: ./configure.sh
      - name: Build LibreCL
        run: cd build && ninja
      - name: Run tests
        run: cd build && ninja check-lcl
