name: Build and Test pipeline

on:
  workflow_call:
    inputs:
      runs-on:
        type: "string"
        required: true
      cargo-flags:
        type: "string"
        required: false
        default: ""

jobs:
  build:
    name: Build runtime
    runs-on: ${{ inputs.runs-on }}
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: Cache build artifacts
      uses: actions/cache@v3
      with:
        path: target
        key: ${{ runner.os }}-build-${{ github.sha }}
        restore-keys: ${{ runner.os }}-build-
    - name: Install dependencies
      run: |
        cargo install cargo-generate-rpm
        cargo install cargo-deb
    - name: Build
      run: cargo build --workspace --no-default-features ${{ inputs.cargo-flags }}
    - name: Package RPM
      run: cargo generate-rpm -p src/runtime
    - name: Package DEB
      run: cargo deb -p librecl_runtime -- ${{ inputs.cargo-flags }}

  runtime_tests:
    name: Run RT tests
    needs: [build]
    runs-on: ${{ inputs.runs-on }}
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: Cache build artifacts
      uses: actions/cache@v3
      with:
        path: target
        key: ${{ runner.os }}-build-${{ github.sha }}
        restore-keys: ${{ runner.os }}-build-
    - name: Install dependencies (macOS)
      if: ${{ runner.os == 'macOS' }}
      run: |
        curl -LsSf https://get.nexte.st/latest/mac | tar zxf - -C ${CARGO_HOME:-~/.cargo}/bin
    - name: Install dependencies (Linux)
      if: ${{ runner.os == 'Linux' }}
      run: |
        curl -LsSf https://get.nexte.st/latest/linux | tar zxf - -C ${CARGO_HOME:-~/.cargo}/bin
    - name: Test
      run: cargo nextest run --all --no-default-features ${{ inputs.cargo-flags }}
