name: Build and Test pipeline

on:
  workflow_call:
    inputs:
      runs-on:
        type: "string"
        required: true
      cargo-flags:
        type: "string"
        required: false
        default: ""

jobs:
  build:
    name: Build runtime
    runs-on: ${{ inputs.runs-on }}
    steps:
    - name: Install Ubuntu dependencies
      if: runner.os == 'Linux'
      run: |
        sudo apt install -yqq ccache ninja-build libtbb-dev spirv-tools
        curl -LsSf https://get.nexte.st/latest/linux | tar zxf - -C ${CARGO_HOME:-~/.cargo}/bin
    - name: Install dependencies (macOS)
      if: ${{ runner.os == 'macOS' }}
      run: |
        brew install ccache ninja tbb ncurses
        curl -LsSf https://get.nexte.st/latest/mac | tar zxf - -C ${CARGO_HOME:-~/.cargo}/bin
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: Cache build artifacts
      uses: actions/cache@v3
      with:
        path: target
        key: ${{ runner.os }}-build-${{ github.sha }}
        restore-keys: ${{ runner.os }}-build-
    - name: Build
      run: cargo build --workspace
    - name: Runtime smoke test
      run: cargo nextest run --all
