name: Android Build and Test pipeline

on:
  workflow_call:
    inputs:
      runs-on:
        type: "string"
        default: 'ubuntu-latest'
        required: false
      cargo-flags:
        type: "string"
        required: false
        default: "--no-default-features --features vulkan --release"

jobs:
  build:
    runs-on: ${{ inputs.runs-on }}
    steps:
      - name: Install Ubuntu dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt install -yqq ninja-build spirv-tools libvulkan-dev
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-11 15
          sudo update-alternatives --install /usr/bin/cc cc /usr/bin/gcc-11 15
          sudo update-alternatives --install /usr/bin/c++ c++ /usr/bin/g++-11 15
          wget -P /tmp/ https://github.com/mozilla/sccache/releases/download/v0.3.0/sccache-v0.3.0-x86_64-unknown-linux-musl.tar.gz
          tar -xvf /tmp/sccache-v0.3.0-x86_64-unknown-linux-musl.tar.gz -C /tmp/
          sudo install /tmp/sccache-v0.3.0-x86_64-unknown-linux-musl/sccache /usr/bin/sccache
          cargo install cargo-ndk
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Cache build artifacts
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/cache
          key: android-build-${{ github.sha }}
          restore-keys: android-build-
      - name: Build
        env:
          RUSTFLAGS: "-D warnings"
          RUSTC_WRAPPER: sccache
          SCCACHE_DIR: ${{ github.workspace }}/cache
        run: cargo ndk -t aarch64-linux-android --bindgen build --workspace -vv ${{ inputs.cargo-flags }}
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ runner.os }}-${{ runner.arch }}-binaries
          path: |
            target/aarch64-linux-android/debug/*lcl_icd_runtime*
            target/aarch64-linux-android/release/*lcl_icd_runtime*
            target/aarch64-linux-android/debug/lcl_compiler/lib*/*lcl_compiler*
            target/aarch64-linux-android/debug/lcl_compiler/bin/*lcl_compiler*
            target/aarch64-linux-android/release/lcl_compiler/lib*/*lcl_compiler*
            target/aarch64-linux-android/release/lcl_compiler/bin/*lcl_compiler*

