name: Postcommit

on:
  push:
    branches:
    - develop

jobs:
  linux:
    name: Linux
    uses: ./.github/workflows/pipeline.yaml
    with:
      runs-on: "ubuntu-22.04"
  macos:
    name: macOS
    uses: ./.github/workflows/pipeline.yaml
    with:
      runs-on: "macos-12"
