name: Precommit

on:
  pull_request:
    branches:
    - develop

jobs:
  linux:
    name: Linux
    uses: ./.github/workflows/pipeline.yaml
    with:
      runs-on: "ubuntu-22.04"
      test-config: "linux"
  android:
    needs: [linux]
    name: Android aarch64
    uses: ./.github/workflows/pipeline-android.yaml
  macos:
    name: macOS
    uses: ./.github/workflows/pipeline.yaml
    with:
      runs-on: "macos-12"
      test-config: "macos"
      # TODO figure out Vulkan builds
      cargo-flags: "--no-default-features --features=metal,online_compiler"
